namespace DeenGames.AliTheAndroid.Infrastructure.Common
{
    public enum Key
    {
        Escape,
        Up,
        Down,
        Left,
        Right,
        Space,
        OemPeriod,
        OemComma,
        A,
        D,
        E,
        F,
        Q,
        S,
        T,
        W,
        NumPad1,
        NumPad2,
        NumPad3,
        NumPad4,
        NumPad5,
        NumPad6,
        NumPad7,
        NumPad8,
        NumPad9,
    }
}